version: '3'
services:
  web:
    build: 
      context: ./app/
      dockerfile: ./Dockerfile
    environment:
      - BASE_DIR=$BASE_DIR
      - VERSION=$VERSION
      - SECRET_KEY=$SECRET_KEY
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - $ETDMOUNT:/app/instance/etd
      - $CHCMOUNT:/app/instance/chc
      - $ARCHIVESMOUNT:/app/instance/archives

  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
